name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'adopt'
        
    - name: Build with Maven
      run: mvn --batch-mode --update-snapshots package
      
    - name: Upload Build Artifact
      uses: actions/upload-artifact@v3
      with:
        name: package
        path: target/*.jar
        
  close-stale-issues:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/stale@v6
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'This issue is stale because it has been open for 30 days with no activity.'
        days-before-stale: 30
        days-before-close: 5
        
  greet-new-contributor:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        pr-message: 'Thank you for your first pull request! We appreciate your contribution to this project.'
        issue-message: 'T
